#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-center ~/.local/share/fondos/fondo.png &
picom --config "$HOME/.config/picom/picom.conf" 2>/dev/null &
/bin/bash $HOME/.config/polybar/launch.sh
